########## Redis cofig start ##########
spring:
  redis:
    database: 0      ## Redis数据库索引（默认为0）
    host: localhost  ## Redis服务器地址(默认为 127.0.0.1)
    port: 6379       ## Redis服务器连接端口（默认为6379）
    pool:
      max-idle: 8    ## 连接池中的最大空闲连接
      min-idle: 0    ## 连接池中的最小空闲连接
      max-active: 8  ## 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1   ## 连接池最大阻塞等待时间（使用负值-1表示没有限制）
########## Redis cofig end ###########